content = open('src/app/pages/Home.tsx').read()
content = content.replace('from-zinc-900/90 via-zinc-900/70 to-zinc-900/20', 'from-zinc-900 via-zinc-900/85 to-zinc-900/40')
content = content.replace('className="max-w-3xl text-white"', 'className="max-w-3xl text-white bg-zinc-900/50 p-8 rounded-lg backdrop-blur-sm"')
open('src/app/pages/Home.tsx', 'w').write(content)
print("Done")
